#!/usr/bin/env node
/**
 * backlog.mjs — regenerate docs/backlog/INDEX.md from the issue files.
 *
 * The issue files are the source of truth. This script only ever writes
 * INDEX.md, so it is safe to run at any time.
 *
 *   node scripts/backlog.mjs          # regenerate INDEX.md
 *   node scripts/backlog.mjs --check  # exit 1 if INDEX.md is stale (for CI)
 *
 * No dependencies — deliberately runnable before `npm install`.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "docs", "backlog");
const INDEX = join(DIR, "INDEX.md");

const STATUS_ORDER = ["in-progress", "blocked", "todo", "done", "wontfix"];
const STATUS_LABEL = {
  "in-progress": "In progress",
  blocked: "Blocked",
  todo: "To do",
  done: "Done",
  wontfix: "Won't fix",
};
const PRIORITY_ORDER = ["P0", "P1", "P2", "P3"];

/** Parse the leading `---` frontmatter block. Values are plain strings. */
function parseFrontmatter(text, file) {
  if (!text.startsWith("---\n")) throw new Error(`${file}: missing frontmatter`);
  const end = text.indexOf("\n---", 4);
  if (end === -1) throw new Error(`${file}: unterminated frontmatter`);
  const out = {};
  for (const line of text.slice(4, end).split("\n")) {
    if (!line.trim()) continue;
    const i = line.indexOf(":");
    if (i === -1) throw new Error(`${file}: bad frontmatter line: ${line}`);
    out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return out;
}

const issues = readdirSync(DIR)
  .filter((f) => /^CC-\d+\.md$/.test(f))
  .map((f) => {
    const fm = parseFrontmatter(readFileSync(join(DIR, f), "utf8"), f);
    for (const k of ["id", "title", "status", "priority", "area", "epic"]) {
      if (!fm[k]) throw new Error(`${f}: missing required field "${k}"`);
    }
    if (!STATUS_ORDER.includes(fm.status)) {
      throw new Error(`${f}: unknown status "${fm.status}" (expected ${STATUS_ORDER.join(", ")})`);
    }
    if (!PRIORITY_ORDER.includes(fm.priority)) {
      throw new Error(`${f}: unknown priority "${fm.priority}"`);
    }
    return { ...fm, file: f };
  });

const byPriority = (a, b) =>
  PRIORITY_ORDER.indexOf(a.priority) - PRIORITY_ORDER.indexOf(b.priority) ||
  a.id.localeCompare(b.id);

const open = issues.filter((i) => i.status !== "done" && i.status !== "wontfix");

// ── header + counts ─────────────────────────────────────────────────────────
const lines = [
  "# Backlog",
  "",
  "Generated by `node scripts/backlog.mjs` — **do not edit by hand.**",
  "Edit the `CC-*.md` files, then regenerate.",
  "",
];

const counts = STATUS_ORDER.map((s) => [s, issues.filter((i) => i.status === s).length]).filter(
  ([, n]) => n > 0,
);
lines.push(
  `**${issues.length} issues** — ` + counts.map(([s, n]) => `${n} ${STATUS_LABEL[s].toLowerCase()}`).join(", "),
  "",
);

const openP = PRIORITY_ORDER.map((p) => [p, open.filter((i) => i.priority === p).length]).filter(
  ([, n]) => n > 0,
);
if (openP.length) {
  lines.push("Open by priority: " + openP.map(([p, n]) => `**${p}** ${n}`).join(" · "), "");
}

// ── open work, grouped by epic then priority ────────────────────────────────
lines.push("## Open", "");
const epics = [...new Set(open.map((i) => i.epic))].sort();
if (!epics.length) lines.push("_Nothing open._", "");

for (const epic of epics) {
  const group = open.filter((i) => i.epic === epic).sort(byPriority);
  lines.push(`### ${epic} (${group.length})`, "");
  lines.push("| ID | P | Status | Area | Title |");
  lines.push("| :-- | :-- | :-- | :-- | :-- |");
  for (const i of group) {
    lines.push(
      `| [${i.id}](${i.file}) | ${i.priority} | ${STATUS_LABEL[i.status]} | ${i.area} | ${i.title} |`,
    );
  }
  lines.push("");
}

// ── closed ──────────────────────────────────────────────────────────────────
const closed = issues.filter((i) => i.status === "done" || i.status === "wontfix");
if (closed.length) {
  lines.push("## Closed", "", "| ID | Status | Title |", "| :-- | :-- | :-- |");
  for (const i of closed.sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`| [${i.id}](${i.file}) | ${STATUS_LABEL[i.status]} | ${i.title} |`);
  }
  lines.push("");
}

// ── Linear provenance ───────────────────────────────────────────────────────
const migrated = issues.filter((i) => i.linear).sort((a, b) => a.id.localeCompare(b.id));
if (migrated.length) {
  lines.push(
    "## Linear provenance",
    "",
    "| ID | Original |",
    "| :-- | :-- |",
    ...migrated.map((i) => `| [${i.id}](${i.file}) | ${i.linear} |`),
    "",
  );
}

const output = lines.join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(INDEX, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== output) {
    console.error("INDEX.md is stale — run `node scripts/backlog.mjs`");
    process.exit(1);
  }
  console.log("INDEX.md is up to date.");
} else {
  writeFileSync(INDEX, output, "utf8");
  console.log(`INDEX.md regenerated — ${issues.length} issues (${open.length} open).`);
}
